
MODEL:
  NAME: "vssm"
  DEVICE_ID: "0"
  PRETRAIN_CHOICE: "imagenet"
  PRETRAIN_PATH: "/home/user/Project/MamReID/TransReID/vssm_base_0229_ckpt_epoch_237.pth"
  DROP_PATH_RATE: 0.3

  TOKEN_ADAPT_ENABLE: True

  CAM_SCALE: 0.0
  VIEW_SCALE: 0.0

  NECK: "bnneck"
  COS_LAYER: False
  ID_LOSS_TYPE: "softmax"
  METRIC_LOSS_TYPE: "triplet"
  IF_LABELSMOOTH: "off"
  IF_WITH_CENTER: "no"
  NO_MARGIN: False
  DIST_TRAIN: False

  VSSM:
    IN_CHANS: 3
    PATCH_SIZE: 4
    EMBED_DIM: 128

    # ===== 반드시 ckpt와 일치 =====
    DEPTHS: [2, 2, 15, 2]
    SSM_RATIO: 2.0
    
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_CONV: 3
    SSM_CONV_BIAS: False
    SSM_FORWARDTYPE: "v05_noz"
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"

    TOKEN_MERGE: True
    TOKEN_PRUNE: True

    MERGE_START: 0
    MERGE_LAYERS: [10,11]
    PRUNE_LAYERS: [1,2,3,4,5]

    FINAL_THRESHOLD: 0.1
    PRUNE_THRESHOLD: 0.25
    PRUNE_SIM: "cos_delta"
    PRUNE_IMP: "l2"

    


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST:  [256, 128]
  PROB: 0.5
  RE_PROB: 0.3
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD:  [0.229, 0.224, 0.225]

DATASETS:
  NAMES: "cuhk03_d" #"msmt17"
  ROOT_DIR: "/home/user/Project/MamReID/data"

DATALOADER:
  SAMPLER: "softmax_triplet"
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: "AdamW"
  MAX_EPOCHS: 600
  BASE_LR: 1e-4
  IMS_PER_BATCH: 64
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: "linear"
  LARGE_FC_LR: False
  BIAS_LR_FACTOR: 1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.01
  WEIGHT_DECAY_BIAS: 0.0
  CHECKPOINT_PERIOD: 50
  LOG_PERIOD: 200
  EVAL_PERIOD: 600

TEST:
  EVAL: False
  IMS_PER_BATCH: 128
  RE_RANKING: False
  WEIGHT: ""
  NECK_FEAT: "before"
  FEAT_NORM: "yes"

OUTPUT_DIR: "../logs/msmt17_vssm_TE2"
